---

- hosts: db
  sudo: yes
  tasks: 
  - name: Install MariaDb Packages
    yum: name=mariadb-server state=present

  - name: Start MariaDB Service
    service: name=mariadb state=started


- hosts: datacenter
  sudo: yes
  tasks: 
  - name: Stop the firewall
    service: name=firewalld state=stopped enabled=False

- hosts: web
  sudo: yes
  vars: 
    http_port: 80
    doc_root: /var/www/html/ansible
    doc_dir: /ansible/

  tasks:
  - name: Install Apache Packages
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: Deploy Apache Server Custom Configuration
    template: src=templates/httpd.j2 dest=/etc/httpd/conf/httpd.conf
    notify: 
      - Restart Apache

  - name: Create Apache Document Root
    file: path={{doc_root}} state=directory

  - name: Deploy Site Config Files
    template: src=templates/index.j2 dest={{doc_root}}/index.html

  - name: Start Apache Service
    service: name=httpd state=started enabled=True


  handlers: 
    - name: Restart Apache
      service: name=httpd state=restarted

